### ISSUE TITLE
Validação de CNPJ

### ISSUE THREAD

**Issue by guilhermetog** [welitonsousa/mask#1]
Olá welitonsousa!
Primeiramente parabéns pela lib! 
Achei mais prática de usar do que as outras soluções disponíveis.

Estou com um problema para validar CNPJ. 
Apesar do cnpj ser válido, a validação não aprova.

Localizei esse trecho do código que verifica o tamanho do numero após o strip, e consta que deve ser igual a 11. 
Acredito que seja 14 o numero correto de digitos do cnpj.

``` 
lib/validations/validations.dart:51

String? cnpj(String? value, {String error = 'CNPJ inválido'}) {
    String numbers = CNPJValidator.strip(value ?? "");
    if (numbers.length != 11 || !CNPJValidator.isValid(value ?? "")) {
      return error;
    }
  }
```

Fiz a alteração localmente e passou a funcionar. Infelizmente se eu migrar o projeto ou der um clean no flutter, eu perco essa alteração.

**Comment by welitonsousa** [comment]
Boa noite Guilherme, fico muito agradecido pelo feedback!
Realmente eu cometi um erro, fica tranquilo que hoje pela manhã eu subo a
sua correção e vc poderá atualizar o package 😄

Em ter., 29 de mar. de 2022 às 00:11, Guilherme Tognetti Rosa <
***@***.***> escreveu:

**Comment by welitonsousa** [comment]
Bom dia Guilherme, a sua atualização foi publicada junto com mais dois
métodos de validações:
*Mask.validations.multiple* e *Mask.validations.compare*, ambos seguem com
exemplos dando ctrl + space

Em ter., 29 de mar. de 2022 às 00:11, Guilherme Tognetti Rosa <
***@***.***> escreveu:

**Comment by guilhermetog** [comment]
Obrigado! Já atualizei! Deu tudo certo!
